version: '3.1'

services:

    api:
        image: thecodingmachine/php:8.1-v4-apache-node14
        ports:
            - 80:80
        environment:
            APACHE_DOCUMENT_ROOT: public/
            PHP_EXTENSION_INTL: 1
            PHP_EXTENSION_GD: 1
            PHP_INI_MEMORY_LIMIT: 1g
            PHP_EXTENSION_XDEBUG: 1
            PHP_INI_XDEBUG__START_WITH_REQUEST: 1
        volumes:
            - ./:/var/www/html

    db:
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
            MYSQL_DATABASE: "$MYSQL_DATABASE"
            MYSQL_USER: "$MYSQL_USER"
            MYSQL_PASSWORD: "$MYSQL_PASSWORD"
        volumes:
            - db:/var/lib/mysql
            
    redis:
        image: redis:4-alpine

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.8
        ports:
            - 33060:80
        environment:
            PMA_HOST: db
            PMA_USER: "$MYSQL_USER"
            PMA_PASSWORD: "$MYSQL_PASSWORD"
        logging: 
            driver: "none"

volumes:
    db:

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.1.0/24
